{
 "title": "Tunnel",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "agent_host", "label": "Tunnel Server", "query": { "query": "label_values(agent_host)" } },
   {
    "name": "msg_type",
    "label": "Message Type",
    "query": {}
   },
   { "name": "Filters" },
   { "name": "text_search", "label": "Text Search" }
  ]
 },
 "panels": [
  { "title": "Tunnel Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tunnel Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"syslog\", msg_type=~\"$msg_type\", server_ip=~\"$agent_host\"} |= \"$text_search\""
    }
   ]
  },
  { "title": "Host Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_memAvailReal{agent_host=~\"$agent_host\"}/snmp_memTotalReal{agent_host=~\"$agent_host\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snmp_omnTunnelHostCPU{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Tunnel Key Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Container CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snmp_omnTunnelContainerCPU{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Connectivity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_omnTunnelAPIConnectivity{agent_host=~\"$agent_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AWCM Connectivity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_omnTunnelAWCMConnectivity{agent_host=~\"$agent_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnel Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_omnTunnelServerStatus{agent_host=~\"$agent_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_omnTunnelLogLevel{agent_host=~\"$agent_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Devices",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "snmp_omnTunnelNumDevices{agent_host=~\"$agent_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "snmp_omnTunnelNumConnections{agent_host=~\"$agent_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Compliant Devices",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "snmp_omnTunnelNumNonCompliant{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devices Blocked by Admin",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "snmp_omnTunnelNumDevicesBlockedByAdm{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devices Not in Allowlist",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "snmp_omnTunnelNumNotInAllowlist{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed HandShake",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "snmp_omnTunnelNumFailedHandshakes{agent_host=~\"$agent_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devices since Start",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "snmp_omnTunnelNumDevicesSinceStart{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Up Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "snmp_omnTunnelProcessUpTime{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Bit Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Upstream Bit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "snmp_omnTunnelUpstreamBitRate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downstream Bit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "snmp_omnTunnelDownstreamBitRate",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tunnel Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "snmp_omnTunnelMemoryVirtual", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "snmp_omnTunnelMemoryResident", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "snmp_omnTunnelMemoryShared", "legendFormat": "__auto" }
   ]
  }
 ]
}